# Build stage
FROM node:16-alpine as build-stage

WORKDIR /app

# Install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy project files
COPY frontend/ .

# Build app
RUN npm run build

# Production stage
FROM nginx:stable-alpine as production-stage

# Copy built files from build stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copy nginx config
COPY deployment/docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]